### ISSUE TITLE
Maximum number of Integrations for this API has been reached.

### ISSUE THREAD

**Issue by dbramwell** [serverless/serverless-websockets-plugin#22]
After a fair few deployments (50 or so?) I get the following:
```
Serverless: Recoverable error occurred (Maximum number of Integrations for this API has been reached.  Please contact AWS if you need additional Integrations.), sleeping for 5 seconds. Try 1 of 4
```
I've tried removing all past versions of my lamba functions, but feel like there must be some underlying 'links' still floating around in the API Gateway. Is there something i'm missing? I see this [comment](https://github.com/serverless/serverless-websockets-plugin/blob/038c44e50135116c76010dfa520be51eb2ceba3a/src/index.js#L152) which seems to imply that this issue shouldn't exist

**Comment by eahefnawy** [comment]
@dbramwell hmmm thanks for reporting this! That's really interesting. The console doesn't really view the "list of integrations", and since you're facing this issue, I'm probably wrong. To fix this we'll probably need a `clearIntegrations()` method like we're doing with routes and authorizers.

A PR is super welcome! 😊

**Comment by jlaitio** [comment]
...in the meantime enjoy this kludge to clean up your API (the result is paginated so you will have to run this multiple times to get rid of more of them):

`aws apigatewayv2 get-integrations --api-id my-api-id --region my-region | jq -r '.Items[].IntegrationId' | xargs -t -n1 aws apigatewayv2 delete-integration --api-id my-api-id --region my-region --integration-id`

**Comment by lolcoolkat** [comment]
@jlaitio when I run your script.. it crashes on a particular id.. like so.

``An error occurred (ConflictException) when calling the DeleteIntegration operation: Cannot delete Integration because it is referenced by the following Routes with Ids: [xysuk6e]``

And it crashes on that every time I restart the command :P Is there any way to tell it not to crash on errors or skip? :)

**Comment by eahefnawy** [comment]
Thanks all! @dbramwell fixed this!
