### ISSUE TITLE
Unresolved resource dependencies [ApiGatewayRestApi] in the Resources block of the template

### ISSUE THREAD

**Issue by zloof** [serverless/serverless-websockets-plugin#24]
I am trying to export the "ApiGatewayRestApi" into the ENV param:
provider:
  environment:
    GW_URL:
      Fn::Join:
        - ""
        - - "https://"
          - Ref: "ApiGatewayRestApi"
          - ".execute-api.${self:custom.region}.amazonaws.com/${self:custom.stage}"
it's return a error 
Unresolved resource dependencies [ApiGatewayRestApi] in the Resources block of the template
it's work fine in regular Serverless project 
see reference 
https://serverless.com/framework/docs/providers/aws/guide/resources/
http://www.goingserverless.com/blog/api-gateway-url

can you help 
Thanks

**Comment by eahefnawy** [comment]
@zloof hmm not sure I'm following, are you using the websockets plugin?

**Comment by zloof** [comment]
Yes, 
At this repository https://github.com/serverless/serverless-websockets-plugin/blob/master/example/src/websocket-client.js#L48 `config.requestContext.domainName`  it get the domainName form `event` and saved it to dynamodb , but I want it as ENV param, auto initialise at `deploy`

**Comment by zloof** [comment]
OK, I can see now that this plugin use ApiGatewayV2 api, and the non websocket use cloudformation template )-:
is there a way to share the `this.apiId`  #https://github.com/serverless/serverless-websockets-plugin/blob/master/src/index.js#L71 and using it as ENV param  ?

**Comment by shortjared** [comment]
This is actually not possible right now, and probably won't be until we get CloudFormation support for API Gateway v2 WebSockets and move this functionality to the core. Unfortunately, it is a chicken and egg problem because of how this plugin works (deployment via api after standard CloudFormation deployment). You could pass it in as an ENV var after the _first_ deployment once you have that statically defined API ID. The way the example was written was because I didn't want to make people have to do deployments twice if they just wanted to deploy and play with things.

**Comment by zloof** [comment]
thanks
