### ISSUE TITLE
Support for multi service deployments

### ISSUE THREAD

**Issue by lolcoolkat** [serverless/serverless-websockets-plugin#9]
I’d like to deploy API Gateway websocket endpoints to 1 single websocket API but from multiple services (or serverless.yml files). Right now I see the plugin deletes the endpoints and creates new on every deployment. Will this be possible when CF is supported? 

For example in 1 serverless.yml i’d like to specify a sendMessage endpoint.. for my chat service and the other connect/disconnect endpoints in another serverless.yml service.

Thanks!

**Comment by shortjared** [comment]
I'd imagine once we have CF support we'll be able to make this work. We could likely do it now via allowing a statically defined API gateway id.

**Comment by lolcoolkat** [comment]
I guess what i'd like to have the plugin do .. is only delete routes that exist in the serverless.yml file within the service im working in. So if i'm in the chat service that only contains a service `sendMessage` it should only delete that function and not the other ones.

Does this make sense? Do you know when CF support will be available for this? Thanks!

**Comment by eahefnawy** [comment]
@lolcoolkat that makes sense. Unfortunately it's a bit complex to implement since deleting routes require the ids of those routes, and we don't really have a way to store state (ie. those generated route ids) in the v1 of the framework since we're relying on CF to do this job (which of course is absent in this plugin).

I guess we could implement a simple state management solution from within the plugin by saving the ids in the home directory or something, or listing all routes in the API and somehow figure out which ones are in serverless.yml.

We just wanted to get this out of the door asap, and all these issues should be fixed with CF support coming soon.

**Comment by lolcoolkat** [comment]
@eahefnawy 

> listing all routes in the API and somehow figure out which ones are in serverless.yml.

Yep this is what I was planning on doing. The code already makes a request to get all the routes in the api gateway you specify.. so it's as simple as just determining which routes you are working with in the serverless.yml when you go and delete routes :)
